---
- name: Create temp directory for doing work in
  command: mktemp -d /tmp/openshift-thanos-XXXXXX
  register: mktemp
  changed_when: False
  check_mode: no

- name: ensure python dependencies
  pip:
    name:
      - openshift
      - passlib